name: build

on:
  push:
    branches:
      - master

jobs:

  base:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - tag: '7.4'
            dockerfile: php74.Dockerfile
          - tag: '8.0'
            dockerfile: php80.Dockerfile

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker hub
        uses: docker/login-action@v1
        with:
          username: cappuc
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-base-${{ matrix.tag }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-base-${{ matrix.tag }}

      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: ./base
          file: ./base/${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          cache-from: |
            type=local,src=/tmp/.buildx-cache
            twentyweb/cms-base:${{ matrix.tag }}
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=all
          push: true
          tags: |
            twentyweb/cms-base:${{ matrix.tag }}


  assets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker hub
        uses: docker/login-action@v1
        with:
          username: cappuc
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: ./assets
          file: ./assets/Dockerfile
          platforms: linux/amd64,linux/arm64
          cache-from: |
            twentyweb/cms-assets:latest
          push: true
          tags: |
            twentyweb/cms-assets:latest


  nginx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker hub
        uses: docker/login-action@v1
        with:
          username: cappuc
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: ./nginx
          file: ./nginx/Dockerfile
          platforms: linux/amd64,linux/arm64
          cache-from: |
            twentyweb/cms-assets:latest
          push: true
          tags: |
            twentyweb/cms-assets:latest


  composer:
    runs-on: ubuntu-latest
    needs:
      - base

    strategy:
      matrix:
        include:
          - tag: '7.4'
            dockerfile: php74.Dockerfile
          - tag: '8.0'
            dockerfile: php80.Dockerfile

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker hub
        uses: docker/login-action@v1
        with:
          username: cappuc
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: ./composer
          file: ./composer/${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          cache-from: |
            twentyweb/cms-composer:${{ matrix.tag }}
          push: true
          tags: |
            twentyweb/cms-composer:${{ matrix.tag }}


  app:
    runs-on: ubuntu-latest
    needs:
      - base

    strategy:
      matrix:
        include:
          - tag: '7.4'
            dockerfile: php74.Dockerfile
          - tag: '7.4-no-puppeteer'
            dockerfile: php74-noPuppeteer.Dockerfile
          - tag: '8.0'
            dockerfile: php80.Dockerfile
          - tag: '8.0-no-puppeteer'
            dockerfile: php80-noPuppeteer.Dockerfile

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker hub
        uses: docker/login-action@v1
        with:
          username: cappuc
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: ./app
          file: ./app/${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          cache-from: |
            twentyweb/cms-app:${{ matrix.tag }}
          push: true
          tags: |
            twentyweb/cms-app:${{ matrix.tag }}


  web-app:
    runs-on: ubuntu-latest
    needs:
      - base

    strategy:
      matrix:
        include:
          - tag: '8.0'
            dockerfile: php80.Dockerfile
          - tag: '8.0-puppeteer'
            dockerfile: php80-puppeteer.Dockerfile

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker hub
        uses: docker/login-action@v1
        with:
          username: cappuc
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: ./web-app
          file: ./web-app/${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          cache-from: |
            twentyweb/cms-web-app:${{ matrix.tag }}
          push: true
          tags: |
            twentyweb/cms-web-app:${{ matrix.tag }}