name: build php

on:
  workflow_call:
    secrets:
      DOCKER_HUB_TOKEN:
        required: true
    inputs:
      tag:
        type: string
      dockerfile:
        type: string

jobs:
  base:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - tag: ${{ inputs.tag }}
            dockerfile: ${{ inputs.dockerfile }}.Dockerfile

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: cappuc
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: ./base
          file: ./base/${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          pull: true
          tags: |
            twentyweb/cms-base:${{ matrix.tag }}

  composer:
    runs-on: ubuntu-latest
    needs:
      - base

    strategy:
      matrix:
        include:
          - tag: ${{ inputs.tag }}
            dockerfile: ${{ inputs.dockerfile }}.Dockerfile

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: cappuc
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: ./composer
          file: ./composer/${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          pull: true
          tags: |
            twentyweb/cms-composer:${{ matrix.tag }}

  web-app:
    runs-on: ubuntu-latest
    needs:
      - base

    strategy:
      matrix:
        include:
          - tag: ${{ inputs.tag }}
            dockerfile: ${{ inputs.dockerfile }}.Dockerfile

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: cappuc
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: ./web-app
          file: ./web-app/${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          pull: true
          tags: |
            twentyweb/cms-web-app:${{ matrix.tag }}

  web-app-puppeteer:
    runs-on: ubuntu-latest
    needs:
      - web-app

    strategy:
      matrix:
        include:
          - tag: ${{ inputs.tag }}-puppeteer
            dockerfile: ${{ inputs.dockerfile }}-puppeteer.Dockerfile
          - tag: ${{ inputs.tag }}-puppeteer-firefox
            dockerfile: ${{ inputs.dockerfile }}-puppeteer-firefox.Dockerfile

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: cappuc
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: ./web-app
          file: ./web-app/${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          pull: true
          tags: |
            twentyweb/cms-web-app:${{ matrix.tag }}

  web-app-unit:
    runs-on: ubuntu-latest
    needs:
      - base

    strategy:
      matrix:
        include:
          - tag: ${{ inputs.tag }}-unit
            dockerfile: ${{ inputs.dockerfile }}-unit.Dockerfile

    if: inputs.tag != '8.1' && inputs.tag != '8.2'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: cappuc
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: ./web-app
          file: ./web-app/${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          pull: true
          tags: |
            twentyweb/cms-web-app:${{ matrix.tag }}
