name: build

on:
  push:
    branches:
      - master

jobs:

  base:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - tag: 7.4
            dockerfile: php74.Dockerfile
          - tag: 8.0
            dockerfile: php80.Dockerfile

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get image tag
        id: image_tag
        run: echo "::set-output name=tag::sha-$(echo ${GITHUB_SHA} | cut -c1-7)"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker hub
        uses: docker/login-action@v1
        with:
          username: cappuc
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: ./base
          file: ./base/${{ matrix.dockerfile }}
          platforms: linux/amd64
          cache-from: |
            twentyweb/cms-base:${{ matrix.tag }}
          push: true
          tags: |
            twentyweb/cms-base:${{ matrix.tag }}