name: build

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  base:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - tag: "8.1"
            dockerfile: php81.Dockerfile
          - tag: "8.2"
            dockerfile: php82.Dockerfile
          - tag: "8.3"
            dockerfile: php83.Dockerfile

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: cappuc
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-base-${{ matrix.tag }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-base-${{ matrix.tag }}

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: ./base
          file: ./base/${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          cache-from: |
            type=local,src=/tmp/.buildx-cache
            twentyweb/cms-base:${{ matrix.tag }}
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=all
          push: true
          tags: |
            twentyweb/cms-base:${{ matrix.tag }}

  assets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: cappuc
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: ./assets
          file: ./assets/Dockerfile
          platforms: linux/amd64,linux/arm64
          cache-from: |
            twentyweb/cms-assets:latest
          push: true
          tags: |
            twentyweb/cms-assets:latest

  composer:
    runs-on: ubuntu-latest
    needs:
      - base

    strategy:
      matrix:
        include:
          - tag: "8.1"
            dockerfile: php81.Dockerfile
          - tag: "8.2"
            dockerfile: php82.Dockerfile
          - tag: "8.3"
            dockerfile: php83.Dockerfile

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: cappuc
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: ./composer
          file: ./composer/${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          cache-from: |
            twentyweb/cms-composer:${{ matrix.tag }}
          push: true
          tags: |
            twentyweb/cms-composer:${{ matrix.tag }}

  web-app:
    runs-on: ubuntu-latest
    needs:
      - base

    strategy:
      matrix:
        include:
          - tag: "8.1"
            dockerfile: php81.Dockerfile
          - tag: "8.2"
            dockerfile: php82.Dockerfile
          - tag: "8.3"
            dockerfile: php83.Dockerfile

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: cappuc
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: ./web-app
          file: ./web-app/${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          cache-from: |
            twentyweb/cms-web-app:${{ matrix.tag }}
          push: true
          tags: |
            twentyweb/cms-web-app:${{ matrix.tag }}

  web-app-puppeteer:
    runs-on: ubuntu-latest
    needs:
      - web-app

    strategy:
      matrix:
        include:
          - tag: "8.1-puppeteer"
            dockerfile: php81-puppeteer.Dockerfile
          - tag: "8.1-puppeteer-firefox"
            dockerfile: php81-puppeteer-firefox.Dockerfile
          - tag: "8.2-puppeteer"
            dockerfile: php82-puppeteer.Dockerfile
          - tag: "8.2-puppeteer-firefox"
            dockerfile: php82-puppeteer-firefox.Dockerfile
          - tag: "8.3-puppeteer"
            dockerfile: php83-puppeteer.Dockerfile
          - tag: "8.3-puppeteer-firefox"
            dockerfile: php83-puppeteer-firefox.Dockerfile

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: cappuc
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: ./web-app
          file: ./web-app/${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          cache-from: |
            twentyweb/cms-web-app:${{ matrix.tag }}
          push: true
          tags: |
            twentyweb/cms-web-app:${{ matrix.tag }}

  web-app-unit:
    runs-on: ubuntu-latest
    needs:
      - web-app

    strategy:
      matrix:
        include:
          - tag: "8.3-unit"
            dockerfile: php83-unit.Dockerfile

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: cappuc
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: ./web-app
          file: ./web-app/${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          cache-from: |
            twentyweb/cms-web-app:${{ matrix.tag }}
          push: true
          tags: |
            twentyweb/cms-web-app:${{ matrix.tag }}
