name: build

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  php:
    strategy:
      matrix:
        include:
          - tag: 8.1
            dockerfile: php81
          - tag: 8.2
            dockerfile: php82
          - tag: 8.3
            dockerfile: php83

    uses: ./.github/workflows/build_php.yml
    with:
      tag: ${{ matrix.tag }}
      dockerfile: ${{ matrix.dockerfile }}
    secrets:
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

  assets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: cappuc
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: ./assets
          file: ./assets/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          pull: true
          tags: |
            twentyweb/cms-assets:latest

