name: build php

on:
  workflow_call:
    inputs:
      tag:
        type: string
      dockerfile:
        type: string

jobs:
  base:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - tag: ${{ inputs.tag }}
            dockerfile: ${{ inputs.dockerfile }}.Dockerfile

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: cappuc
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-base-${{ matrix.tag }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-base-${{ matrix.tag }}

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: ./base
          file: ./base/${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          cache-from: |
            type=local,src=/tmp/.buildx-cache
            twentyweb/cms-base:${{ matrix.tag }}
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=all
          push: true
          tags: |
            twentyweb/cms-base:${{ matrix.tag }}

  composer:
    runs-on: ubuntu-latest
    needs:
      - base

    strategy:
      matrix:
        include:
          - tag: ${{ inputs.tag }}
            dockerfile: ${{ inputs.dockerfile }}.Dockerfile

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: cappuc
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: ./composer
          file: ./composer/${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          cache-from: |
            twentyweb/cms-composer:${{ matrix.tag }}
          push: true
          tags: |
            twentyweb/cms-composer:${{ matrix.tag }}

  web-app:
    runs-on: ubuntu-latest
    needs:
      - base

    strategy:
      matrix:
        include:
          - tag: ${{ inputs.tag }}
            dockerfile: ${{ inputs.dockerfile }}.Dockerfile

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: cappuc
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: ./web-app
          file: ./web-app/${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          cache-from: |
            twentyweb/cms-web-app:${{ matrix.tag }}
          push: true
          tags: |
            twentyweb/cms-web-app:${{ matrix.tag }}

  web-app-puppeteer:
    runs-on: ubuntu-latest
    needs:
      - web-app

    strategy:
      matrix:
        include:
          - tag: ${{ inputs.tag }}-puppeteer
            dockerfile: ${{ inputs.dockerfile }}-puppeteer.Dockerfile
          - tag: ${{ inputs.tag }}-puppeteer-firefox
            dockerfile: ${{ inputs.dockerfile }}-puppeteer-firefox.Dockerfile

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: cappuc
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: ./web-app
          file: ./web-app/${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          cache-from: |
            twentyweb/cms-web-app:${{ matrix.tag }}
          push: true
          tags: |
            twentyweb/cms-web-app:${{ matrix.tag }}

  web-app-unit:
    runs-on: ubuntu-latest
    needs:
      - web-app

    strategy:
      matrix:
        include:
          - tag: ${{ inputs.tag }}-unit
            dockerfile: ${{ inputs.dockerfile }}-unit.Dockerfile

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: cappuc
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: ./web-app
          file: ./web-app/${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          cache-from: |
            twentyweb/cms-web-app:${{ matrix.tag }}
          push: true
          tags: |
            twentyweb/cms-web-app:${{ matrix.tag }}

